### PR TITLE
Laptop

### PR DESCRIPTION
**Pull request by kimz1121**

### CODE REVIEW

**Comment by rgalljamov** [comment]
Hi @kimz1121, 

I'm happy to see that you're using the code. I hope you find it useful. 

I noticed that you're frequently creating pull requests, which I think might be unintentional. To avoid this, please fork the repository. This will create a copy of the repository under your own GitHub account where you can freely make changes and push updates.You can easily find out how to fork a repository by searching online.

Thanks again for using the code and for your understanding!

Best regards and best luck with your project,
Rustam

**Comment by kimz1121** [comment]
Oh.... i'm so*100 sorry about this situation....😥
It wasn't intentioned and I just noticed...
I feel really sorry for the inconvenience caused by my poor use of git
l'm addressing this problem right now and prevent it from happening again.

Thank you for kindly informing me about this situation and problem even though it's definitely my fault

"I'm happy to see that you're using the code. I hope you find it useful."
->Your repository was really useful! I compared a few other repositories before my project and your code is best organized among them👍

**Comment by rgalljamov** [comment]
Hi @kimz1121,

thank you very much for your kind reply and especially the very swift reaction. There were no more pull requests since 3 days 👍 
Please don't worry and feel sorry, as it was not a big inconvenience for me. In contrary I was happy seeing you using and adapting the code.

Thank you very much for your kind words and all the best with your project! I would happily offer support but need to focus on other projects in the moment.

Best regards and best luck from Germany!
Rustam

**Comment by kimz1121** [comment]
@rgalljamov Thanks for the luck from Germany 🤣 
my final porject had finished great, I think it's thanks to the luck you gave for me!
I'm happy and thank enough for thinking about the help

Best regards and best luck from South Korea!
kimz1121

**Comment by rgalljamov** [comment]
@kimz1121, I'm happy to hear your project finished successfully! :D
Thank you for the kind words and also all the best to you!
Rustam

**Pull request closed without merging**
